---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-microservice-stable
  labels:
    app.kubernetes.io/name: scheduler-microservice-stable
    app.kubernetes.io/part-of: application-layer
    app.kubernetes.io/component: backend-application
    app.kubernetes.io/version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scheduler-microservice-stable
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scheduler-microservice-stable
        app.kubernetes.io/part-of: application-layer
        app.kubernetes.io/component: backend-application
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
        - name: scheduler-microservice
          image: 904333181156.dkr.ecr.sa-east-1.amazonaws.com/scheduler-microservice:$ECR_TAG
          env:
            - name: NATS_CONNECTION_STRING
              value: nats://nats.nats.svc.cluster.local:4222

            - name: MONGODB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: scheduler-microservice
                  key: mongodb-connection-string