---
kind: Service
apiVersion: v1
metadata:
  name: scheduler-microservice-stable
  labels:
    app.kubernetes.io/name: scheduler-microservice-stable
    app.kubernetes.io/part-of: application-layer
    app.kubernetes.io/component: service
    app.kubernetes.io/version: 1.0.0
spec:
  selector:
    app.kubernetes.io/name: scheduler-microservice-stable