version: "3"

services:
  nats:
    image: nats
    restart: unless-stopped
    ports:
      - ${NATS_PORT:-4222}:4222
      - ${NATS_MONITORING_PORT:-8222}:8222


  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - ${MONGODB_PORT:-27017}:27017


  scheduler-microservice:
    build: .
    links:
      - nats
    environment:
      NATS_CONNECTION_STRING: nats://nats:4222
      MONGODB_CONNECTION_STRING: mongodb://username:password@mongo