version: "3"

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - ${MONGODB_PORT:-27017}:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 1s
    networks:
      - bud-scheduler

  scheduler:
    build: .
    depends_on:
      mongo:
        condition: service_healthy
    links:
      - mongo
    environment:
      MONGODB_CONNECTION_STRING: mongodb://username:password@mongo:27017/
      RABBITMQ_CONNECTION_STRING: amqp://guest:guest@rabbitmq:5672
    networks:
      - bud-rabbitmq
      - bud-scheduler

networks:
  bud-rabbitmq:
    external: true
  bud-scheduler:
