---
kind: Service
apiVersion: v1
metadata:
  name: scheduler-microservice-canary
  labels:
    app.kubernetes.io/name: scheduler-microservice-canary
    app.kubernetes.io/part-of: application-layer
    app.kubernetes.io/component: backend-application
    app.kubernetes.io/version: 1.0.0
spec:
  selector:
    app.kubernetes.io/name: scheduler-microservice-canary